---
- name: "Ensures directories exist"
  file: path={{item}} state=directory
  with_items:
    - "{{ glpi_files_root }}"

- name: "Check if path exists"
  stat:
      path: "{{ glpi_install_dir }}"
  register: check_path

# install glpi version if it does not exist
- name: "Install GLPI"
  import_tasks: install.yml
  when: check_path.stat.exists == false

# copy the configurations
- name: "Copy Configurations"
  import_tasks: config.yml

# cleanup some files
- name: "Cleanup"
  import_tasks: cleanup.yml

# make sure the symlink glpi exists and points to the installed version
- name: "Ensure link exists"
  file:
    path: "{{ item }}"
    state: link
    src: "{{ glpi_install_dir }}"
  with_items:
    - "{{ glpi_home_dir }}"

# install plugins
- name: "install plugins"
  include_tasks: plugin.yml
  vars:
    plugin_name: "{{item.key}}"
    plugin_url: "{{item.value.url}}"
    plugin_file:  "{{item.value.url | basename }}"
    plugin_version: "{{item.value.version}}"
    plugin_rename:  "{{item.value.rename | default('')}}"
    tar_params: "{{item.value.url | match('.*bz2$') | ternary('-xvjf','-xvzf')}}"
  with_dict: "{{glpi_plugins}}"

- name: "create /files/ directories"
  file:
    path: "{{ glpi_files_root }}/files/{{item}}"
    state: directory
    owner: http
    group: http
    mode: 0750
  with_items:
    - "{{glpi_dirs}}"

# Set file permissions
- name: "Permissions"
  import_tasks: perms.yml

- name: "Update GLPI"
  import_tasks: update.yml
