---
- name: "[GLPI] Ensures directories exist"
  file: path={{item}} state=directory
  with_items:
    - "{{ glpi_files_root }}"

- name: "[GLPI] Check if path exists"
  stat:
      path: "{{ glpi_install_dir }}"
  register: check_path

# install glpi version if it does not exist
- name: "[GLPI] Install GLPI"
  include: install.yml
  when: check_path.stat.exists == false

# copy the configurations
- name: "[GLPI] Copy Configurations"
  include: config.yml

# cleanup some files
- name: "[GLPI] Cleanup"
  include: cleanup.yml

# make sure the symling glpi exists and points to the installed version
- name: "[GLPI] Ensure link exists"
  file:
    path: "{{ item }}"
    state: link
    src: "{{ glpi_install_dir }}"
  with_items:
    - "{{ glpi_home_dir }}"

# install plugins
- name: "[GLPI] install plugins"
  include: plugin.yml
  vars:
    plugin_name: "{{item.key}}"
    plugin_url: "{{item.value.url}}"
    plugin_file:  "{{item.value.url | basename }}"
    plugin_version: "{{item.value.version}}"
    plugin_rename:  "{{item.value.rename | default('')}}"
  with_dict: "{{glpi_plugins}}"

# Set file permissions
- name: "[GLPI] Permissions"
  include: perms.yml
