---
- name: "[GLPI] Check if Plugin {{plugin_name}} needs update"
  stat:
    path: "{{glpi_install_dir}}/plugins/{{plugin_name}}/version_{{plugin_version}}"
  register: plugin_exists

- name: "[GLPI] Download Plugin {{plugin_name}}"
  get_url:
    url: "{{plugin_url}}"
    dest: "{{glpi_dl_tmp}}/{{plugin_file}}"
  when: plugin_exists.stat.exists == False

- name: "[GLPI] extract plugin archive {{plugin_file}}"
  command:  tar -xvzf {{glpi_dl_tmp}}/{{plugin_file}}
  args:
    chdir: "{{glpi_install_dir}}/plugins"
    creates: "{{glpi_install_dir}}/plugins/{{plugin_name}}/version_{{plugin_version}}"
  register: plugin_changed
  when: plugin_exists.stat.exists == False

- name: "[GLPI] update version file"
  file:
    path: "{{glpi_install_dir}}/plugins/{{plugin_name}}/version_{{plugin_version}}"
    state:  touch
  when: plugin_changed.changed
